- .github/workflows/publish.yml
- .vscodeignore
- package.json
Removes additional dependencies and code when installing the plugin, should speed up installing the plugin.
- `$ yarn build` creates a non-minified build using `node_modules`, ideal for developing
- `$ yarn build:production` creates a minified build without the need of `node_modules`, ideal for production
> fix: remove extraneous files when packaging

- src/manifest/__tests__/__mocks__/json-schema-traverse.ts
- src/manifest/__tests__/schema.test.ts
Adds the missing test to fall back on the simple (non-enhanced) schema.
> chore: add missing test when failing to enhance schema

- .prettierrc.js
- src/manifest/__tests__/index.test.ts
- src/manifest/__tests__/schema.test.ts
- src/manifest/index.ts
- src/manifest/schema.ts
- test/fixtures/schema-enhanced-39.0.0.json
- test/fixtures/schema-plugin-39.0.0.json
- test/fixtures/schema-xdl-39.0.0.json
Adds the `schema.meta.bareWorkflow` notes to the descriptions of the schema. It's the property that we also render on the docs, but integrated within the tooltip/intellisense.
- Part of #17
> fix: add missing bare workflow notes to schema

- .vscode/launch.json
- package.json
- patches/@expo+config-plugins+1.0.29.patch
- webpack.config.js
- yarn.lock
This disables the `@expo/config-plugins` `require` modification by webpack.
Also added an extra launch script that runs the extension locally in production mode.
> fix: add webpack ignore patch to dynamic config plugins import

- src/manifest/configPlugins.ts
- src/manifest/fileReferences.ts
- src/manifest/utils/iteratePlugins.ts
- tsconfig.json
- Support `⌘ click` to visit a file reference matching `"(\./\.*)"` (the reference must be outside of the plugins array).
- Support showing a diagnostic error when a file reference doesn't exist relative to the project root. Missing files can still be linked to in case the user wants to jump to the location and press `⌘s` to create the file.
- Make all diagnostic errors exclude the quotes around a string.
> Link to assets and file references

- src/preview/ExpoConfigCodeProvider.ts
Previews of the config throw errors because assets cannot be resolved relative to `/`, this PR names the template preview filename `_app.config.json` to disable file matching against it. Bit of a hack, but it seems to be the best solution for right now.
> fix: disable helpers on preview files

- src/preview/IntrospectCodeProvider.ts
If the user changes the app name in the config then the config will stop updating because the URI was changing on iOS. This PR changes the providers to use static names that can't be changed.
> fix: app name change breaking ios previews

- src/preview/CodeProvider.ts
- src/preview/setupPreview.ts
- Open a modifier preview.
- Modify the file so that new code is added.
- Modified lines should turn green.
- Changes should update on each modification.
Utilizes a lot of built in features so it's pretty reliable and quick
> feature: apply styles to modified preview lines

- package.json
- webpack.config.js
- yarn.lock
This should get `yarn build:production` up and running again, and way faster than before 😄 
- To properly resolve `.d.ts` files in `node_modules`, we need to remove the `include: src` scope
- To avoid trying to bundle `fsevents.node`, we need to add the node externals
The last time I tried this, it resulted in broken builds. But this time it seems to work like a charm!
> fix: resolve webpack bundling issues for production

- package.json
- patches/xdl+59.0.46.patch
- webpack.config.js
With Webpack external, some fundamental libraries are excluded. Let's fix them by using the list of breaking and not-required dependencies.
Also fixed the release tokens.
> fix: missing required libraries and make webpack work with xdl

- .github/workflows/publish.yml
- package.json
This allows us to directly reference the package, without using the vscode marketplace. Ideal for [environments like gitpod](https://www.gitpod.io/docs/vscode-extensions).
> chore: add package as release assets for open-source usage

- .github/workflows/test.yml
- package.json
- yarn.lock
Its mentioned when packaging the extension:
>  WARNING  Using '*' activation is usually a bad idea as it impacts performance.
> More info: https://code.visualstudio.com/api/references/activation-events#Start-up
Let's switch to after it's fully started.
We might want to look into more complex startup events, like only start when a package.json file exists and has expo as dependency.
> fix!: activate extension after vscode is ready

- src/manifest/configPlugins.ts
Fixes the plugin path (alt + click) on Windows machines.
> fix: parse file paths as uri as file explicitly

- README.md
A bit wack that Github decided to break this behavior, but it should clean the header up again!
> docs: clean up header of readme

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- package.json
- test/jest/cli.ts
- test/jest/runner.ts
- yarn.lock
> chore: update workflows with concurrency

- README.md
Minor but semantically important change.
> [docs] README - app.config.js, not .json

- .github/actions/setup-project/action.yml
- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
This does a couple of things:
- Bumps up Node versions in workflows
- Bumps up action versions
- Adds a default setup action
> chore: upgrade workflows and use default setup action

- package.json
We also support `app.config.json`
> fix: enable expo xdl intellisense on app.config.json

- .github/workflows/publish.yml
Fixes #84
Already [published the latest `0.7.4` to Open VSX](https://open-vsx.org/extension/byCedric/vscode-expo).
> chore: add publish to open-vsx

- package.json
Fixes #113
There is no automated workflow to manage this schema yet. I'll keep the original issue open because of that. We have a few options:
1. Try to infer the json schema through typedoc from https://cdn.jsdelivr.net/npm/expo-modules-autolinking@0.9.0/build/types.d.ts
2. Add a schema to `expo-modules-autolinking` that we update here, just like `eas-metadata.json`
The manual schema lives here: https://github.com/expo/vscode-expo/blob/schemas/schema/expo-module.json
> feature: add expo-module.config.json intellisense

- .github/workflows/schema-metadata.yml
- .github/workflows/schema-xdl.yml
This should minimize the amount of "failure" in the schema workflows.
Copied from https://github.com/expo/expo-github-action/commit/ee415b027afce4c15cabcc6fa2f8368530a36c08
Tested workflows:
- schema-eas-metadata - https://github.com/expo/vscode-expo/actions/runs/2796479961
- schema-expo-xdl - https://github.com/expo/vscode-expo/actions/runs/2796481842
> chore: only commit schema changes when actually changed

- .github/workflows/schema-eas.yml
- .github/workflows/schema-metadata.yml
This adds an automated workflow to keep `schemas/eas.json` up to date.
The ownership of this schema is now moved to the expo/eas-cli repository. Before merging this PR:
Tested workflow:
- schema-metadata, with `latest`, https://github.com/expo/vscode-expo/actions/runs/2796676695
- schema-metadata, with `0.56.0`, https://github.com/expo/vscode-expo/actions/runs/2796683490
> chore: add automated eas schema workflow

- src/manifest/fileReferences.ts
- src/manifest/utils/iteratePlugins.ts
- src/manifest/utils/parseExpoJson.ts
We don't need to iterate over every node, we can just ask `jsonc` to find nodes at `expo.plugins` or something like that.
> refactor: use node lookup method instead of custom code

- package.json
Fixes #66
Note that we support JSON5 instead of the non-spec-conform-thing called "JSON with Comments (JSONC)". Unfortunately, this is what ships with vscode by default. JSON5 isn't available without other extensions that register the grammar.
See: https://github.com/microsoft/vscode/issues/100688
> fix: set language for app manifests and eas to jsonc

- package.json
Fixes #135
This sets the default to `null`, exactly how we use it in the configuration fetching code.
> fix: set `null` as default for exclude glob patterns

- src/manifest/utils/parseExpoJson.ts
This fixes #139, turns out to be the language filter. That was changed in the fix for #66.
> fix: app manifest asset linking

- .vscode/launch.json
- test/jest/runner.ts
This is great when focusing on a single Jest file. You only have to open that file and run this new `Test: current file (development)` to only run those tests.
> chore: add current file test launch option

- src/expo/project.ts
- src/utils/cache.ts
Add an Expo project cache to keep track of one or more projects within a workspace. This is useful when we move functionality to dedicated providers.
> feature: add expo project cache for efficient json parsing

- package.json
- yarn.lock
Turns out to be the Tabs API we use in testing. But even with this version, we still have ±6 months of versions backward compatible. I think that's more than enough.
> chore: bump vscode to min 1.67.0

- src/__tests__/manifestDiagnostics.e2e.ts
- src/__tests__/manifestPluginCompletions.e2e.ts
- src/completion/provider/createCompletionItem.ts
- src/completion/provider/provideCompletionItems.ts
- src/expo/manifest.ts
- src/expo/plugin.ts
- src/extension.ts
- src/manifestDiagnostics.ts
- src/manifestLinks.ts
- src/manifestPluginCompletions.ts
- src/settings.ts
- src/utils/array.ts
- src/utils/file.ts
- src/utils/json.ts
- src/utils/vscode.ts
This should replace the `src/completion` functionality, except the asset suggestions.
> feature: add manifest plugin completion provider

- package.json
- src/expo/plugin.ts
- src/settings.ts
- src/utils/debug.ts
- src/utils/file.ts
- src/utils/json.ts
Cleaning up the codebase, after dropping most except the preview code.
> refactor: drop unused code after dropping most superseded code

- .github/workflows/publish.yml
- package.json
- yarn.lock
Unfortunately, semantic release has a sub-optimal way of creating prereleases, so these have to be done by hand. But, when created, we can publish the prerelease as the actual prerelease to marketplace and openvsx.
> chore: upgrade to latest vsce and support prerelease publish

- src/__tests__/manifestDiagnostics.e2e.ts
- src/manifestDiagnostics.ts
This makes sure the plugin never keeps outdated information of plugins, e.g. when installing a new plugin and trying to validate the same manifest again.
> fix: always diagnose plugins from an empty modules cache

- src/__tests__/manifestDiagnostics.e2e.ts
- src/utils/module.ts
When defining plugins like `expo-build-properties`, before installing, the old "could not find module" result is cached in Node's own `require`/module cache. This should empty out plugins from modules as well.
> fix: reset plugins from modules when diagnosing

- .github/workflows/test.yml
- package.json
- test/jest/cli.ts
- yarn.lock
Seems that there might be false failures on #174, this should make the headless vscode testing a bit more stable.
The issue seems to be introduced with in `1.78.x`, pinning the version down to `1.77.x` until its resolved. There is an experimental workflow that keeps testing newer versions to see if its resolved.
See: https://github.com/microsoft/vscode/issues/152938
> chore: swap to `coactions/setup-xvfb` for more stable headless vscode tests

- README.md
- package.json
Exciting times ahead for the vscode plugin!
→ ~~Pending infra deployment~~
→ Done!
→ See https://github.com/EclipseFdn/open-vsx.org/issues/1831
→ Thanks to @kineticsquid, this is now done: https://open-vsx.org/extension/expo/vscode-expo
→ ~~Reached out, awaiting reply~~
While the [OpenVSX community is awesome in terms of support](https://github.com/EclipseFdn/open-vsx.org/issues/1831#issuecomment-1551490914), and transferability, @microsoft doesn't allow this. I'll deprecate `byCedric.expo-tools`, after we published `expo.expo-tools` on the vscode marketplace.
It's an absolute bummer, since we lose all reviews and downloads so far, but it is what it is.
> refactor: change publisher to `expo`

- src/expo/bundler.ts
- src/expo/project.ts
- src/expoDebuggers.ts
We can't infer the project type (and thus "guess" on what port Metro is running) from the folders alone.
You can run a prebuilt project without having `/android` and `/ios` folders, and you can start a classic Expo project in dev client mode with `npx expo start --dev-client`.
Instead, we just try to connect to either `8081` or `19000` and see which one succeeds.
> fix: replace unreliable workflow detection with multiple connection attempts

- test/fixture/config-js-app/package.json
- test/fixture/config-ts-app/package.json
- test/fixture/package.json
- test/jest/environment.ts
This also automatically adds the fixtures to the workspaces, and solves some conflicting fixture names.
> chore: treat all fixtures as non-monorepo projects

- src/expoDebuggers.ts
Fixes #186
By adding this to the sourcemaps, the error should not pop up again.
> fix: mute `react-devtools-core` sourcemap missing error

- package.json
Just some missing information for vscode.
> fix: add missing `ms-vscode.js-debug` dependency and activate in expo monorepos

- package.json
Starting from SDK 49, this is now the default port for both `expo-dev-client` _and_ Expo Go projects.
> chore: update debugging snippet using `8081` as default port

- src/expoDebuggers.ts
Found a small issue in the regex sourcemap lookup. It should not affect anyone but might cause some confusing explanations when debugging unbound breakpoints.
> fix: add missing `bundlerPort` for `remoteRoot` when debugging apps

- .github/workflows/release.yml
> chore: add missing `permissions` to github workflow when dry-running release

- package-lock.json
- package.json
This is a realignment of both the CI tests, as well as aligning this version with the current telemetry.
Supersededs #193
> refactor: bump minimum vscode version to `1.78.2`

- .github/actions/test-vscode/action.yml
- .github/workflows/test.yml
Part of the maintenance release.
> chore: clean up log-clutter in test output

- src/__tests__/commands/code-provider.e2e.ts
- src/expo/plugin.ts
- src/extension.ts
- src/packages/config-plugins.ts
- src/packages/config.ts
- src/packages/plist.ts
- src/packages/prebuild-config.ts
- src/preview/CodeProvider.ts
- src/preview/ExpoConfigCodeProvider.ts
- src/preview/IntrospectCodeProvider.ts
- src/preview/setupPreview.ts
Supersedes #216
We need to decouple the dependence on @expo/* package a bit. This is the first step.
> refactor: emphasize bundled `@expo/*` packages and limit imports

- schema/expo-module.json
Updating the schema for `expo-module.config.json` that includes `apple`, `macos`, `tvos` and `devtools` platforms
> Update schema for expo-module.config.json

- src/expoDebuggers.ts
See PR expo/expo#25649, specifically [this line](https://github.com/expo/expo/pull/25649/files#diff-8be445febc4537dfa7db7961c4d7f60ad9e1af9ada0cb99db9cfba1d3b54f788R106)
VSCode doesn't send any `User-Agent` headers when connecting through web sockets. This differs from the Chrome DevTools, where we can safely detect this Chrome-based debugger. Since we have some workarounds for known React Native CDP (as opposed to the future Hermes CDP) implementation.
- Test this once a `canary` release is available with expo/expo#25649
> fix: add `userAgent` query parameter in debugger

- src/expoDebuggers.ts
This is related to a behavior change from vscode, and to microsoft/vscode#188979.
> fix: only change to underlying vscode adapter when starting debug session

- src/expo/__tests__/project.test.ts
- src/expo/plugin.ts
- src/expo/project.ts
- src/expoDebuggers.ts
- src/manifestAssetCompletions.ts
- src/manifestDiagnostics.ts
- src/manifestLinks.ts
- src/manifestPluginCompletions.ts
- src/utils/__tests__/file.test.ts
- src/utils/cache.ts
- src/utils/file.ts
We already used most of the `vscode.workspace.fs` API, but not to load Expo projects. That still happened through `fs.` calls. This fully removes all `fs.` calls when loading Expo projects.
> feature: use `vscode.workspace.fs` API to load Expo projects

- .github/workflows/test.yml
This should pro-actively warn us about vscode API changes.
> chore: enable tests for vscode insiders versions

- package.json
This is because `workspaceContains:node_modules/expo` doesnt work for non-top-level references.
See: https://github.com/Microsoft/vscode/issues/2739
> fix: activate extension after startup is finished

- src/manifestAssetCompletions.ts
This is being reported as an unhandled promise error. This should solve that.
> fix: use optional chaining when validating relative paths in manifest asset completions

- src/expo/project.ts
It is being reported as unhandled promise exception, which should never happen. This PR makes the `workspace.fs.stat` a safe operation by wrapping it in try catch, and aborting where necessary.
> fix: add `workspace.fs.stat` error handling when files are missing

- src/expo/__tests__/bundler.test.ts
- src/expo/bundler.ts
It's not ideal, but it should cover more cases. We need to know on what platform issues occur, so we can fix them.
> feature: add more infers to determine device platform when debugging

- src/expo/__tests__/bundler.test.ts
- src/expo/bundler.ts
This is to avoid connecting to the dev menu, or expo go bundle itself.
> fix: use highest page number whenever multiple identical pages are connected

- package-lock.json
- src/expo/__tests__/bundler.test.ts
- src/expo/bundler.ts
Provide the issue(s) which this pull request relates to or fixes.
- fixes: https://github.com/expo/vscode-expo/issues/271
Are there things the maintainers should be aware of before merging or closing this pull request?
This PR fixes:
- Version misalignment in the lock file
- Expo Go filtering test
- Expo Go filtering after https://github.com/expo/expo/commit/f545f30fe1df3dd0d346b12aa65a2feb7cb27439
- Filter Reanimated UI Inspectable target
<details>
<summary>Details</summary>
Filter out `Reanimated UI runtime`
```
{
"id": "027caaae50b565d3dcf71a35ae72343af5381b76-1",
"title": "com.krystofwoldrich.ToTheMoon (iPhone 16)",
"description": "React Native Bridgeless [C++ connection]",
"appId": "com.krystofwoldrich.ToTheMoon",
"type": "node",
"devtoolsFrontendUrl": …
```
> fix(bundler): Device filtering in SDK 53
