.github/workflows/build.yml, .github/workflows/publish.yml, .github/workflows/test.yml, package.json, yarn.lock
This makes it easier to maintain, and faster to see if stuff works as expected.
Testing still needs to be added.
=> chore: deploy from ci and improve performance

package.json, tsconfig.json, yarn.lock
Split out of https://github.com/expo/vscode-expo/pull/39
=> Bump to node 12

.github/workflows/release.yml, .releaserc.js, CONTRIBUTING.md, package.json, yarn.lock
This adds a workflow and an automated way to create a new release with semantic-release.
This will be the flow:
- Start a new release
- Parses commits from the last tag
- Updates changelog
- Updates package version
- Commit to repo with new tag
- Create a new GH release
- Once a new GH release is created
- Send it to vscode marketplace, in separate workflow
=> chore: setup up automated release flow and usage documentation

src/preview/IntrospectCodeProvider.ts, src/preview/setupPreview.ts
Sometimes the results change order but don't actually change, this PR aims to fix that by sorting the keys of the object (JS anti-pattern).
=> fix: sort mod result keys

package.json, patches/@expo+config-plugins+4.0.7.patch, patches/xdl+59.2.10.patch, patches/xdl+59.2.13.patch, src/preview/IntrospectCodeProvider.ts, src/preview/setupPreview.ts, yarn.lock
Appears to fix the issues related to intellisense, but I only ran it in dev mode.
Are there things the maintainers should be aware of before merging or closing this pull request?
=> fix: config plugin validation by upgrading dependencies

src/manifest/schema.ts, test/fixtures/schema-enhanced-39.0.0.json, test/fixtures/schema-enhanced-41.0.0.json, test/fixtures/schema-plugin-39.0.0.json, test/fixtures/schema-plugin-41.0.0.json
=> fix: remove required expo root from app json file

package.json, yarn.lock
=> chore: upgrade vsce to 2.9.2

package.json, patches/@expo+config-plugins+4.1.5.patch, src/preview/CodeProvider.ts, src/preview/ExpoConfigCodeProvider.ts, src/preview/IntrospectCodeProvider.ts, webpack.config.js, yarn.lock
Maintenance update, just to keep everything compatible with the latest config plugins.
=> chore: upgrade all expo dependencies

README.md
=> docs: update eas managed workflow documentation

README.md
This should make things a bit better in terms of how to use things etc.
Also added links to prebuild, added missing preview modifier, and removed eject
=> docs: rework the main readme file

.github/actions/setup-project/action.yml, .github/workflows/test.yml
I noticed the cache takes +- 5 min on windows, so disabling it for windows.
=> chore: add option to disable cache

package.json
=> fix: set command category instead of in title

src/manifestDiagnostics.ts, src/manifestLinks.ts, src/manifestPluginCompletions.ts
Makes getting into the code slightly easier.
=> docs: add comments for individual chunks of code

src/__tests__/manifestAssetCompletions.e2e.ts, src/__tests__/manifestPluginCompletions.e2e.ts, src/__tests__/schemas/eas-metadata.e2e.ts, src/__tests__/schemas/eas.e2e.ts, src/__tests__/schemas/expo-module.e2e.ts, src/__tests__/schemas/expo-xdl.e2e.ts, src/__tests__/utils/vscode.ts, src/__tests__/utils/wait.ts
Update the existing tests to be more resilient and performant.
=> refactor: update tests with new tricks to improve stability and performance

.vscode/launch.json, package.json, src/expo/bundler.ts, src/expo/project.ts, src/expoDebuggers.ts, src/extension.ts, src/utils/vscode.ts, yarn.lock
The debugger only works for apps running Hermes, but it's quite powerful.
=> feature: add debugger for Expo apps using Hermes

package.json, src/expo/bundler.ts, src/expoDebuggers.ts, src/utils/telemetry.ts, yarn.lock
To make this a great option, we'd need to know how it's being used, and what edge cases it runs into.
=> chore: improve telemetry around debugging

README.md
=> docs: add section about debugging in the readme

README.md, package.json
Fixes [ENG-8829](https://linear.app/expo/issue/ENG-8829/expo-tools-vs-code-extension-notes)
Just some documentation polishes.
=> docs: update wording and descriptions

src/expo/bundler.ts, src/utils/__tests__/array.test.ts, src/utils/array.ts
This is caused by Reanimated adding another inspector target, but Metro not being able to return that with a different name.
This will likely be fixed in a later version of Metro. Once that happens, we can test the Reanimated target in this extension.
```
[
{
"id": "0-1",
"description": "com.bycedric.blank49bare",
"title": "Hermes React Native",
"faviconUrl": "https://reactjs.org/favicon.ico",
"devtoolsFrontendUrl": "devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=%5B%3A%3A%5D%3A8081%2Finspector%2Fdebug%3Fdevice%3D0%26page%3D1",
"type": "node",
"webSocketDebuggerUrl": "ws://[::]:8081/inspector/debug?device=0&page=1",
"vm": "Hermes",
"deviceName": "iPhone SE (3rd generation)"
},
{
"id": "0--1",
"description": "com.bycedric.blank49bare",
"title": "React Native …
```
=> fix: filter duplicate devices on first occurence

package.json, src/__tests__/utils/vscode.ts
Part of some maintenance work.
=> chore: test activation and remove useless activation event

.vscode/launch.json, test/mocha/vscode-runner.ts
There is an unclear difference between local testing and CI testing, this should make that more clear.
=> chore: unify snapshot behavior on CI and local testing

.github/workflows/publish.yml, .github/workflows/release.yml
=> chore(ci): rotate and update repository secrets

.github/actions/setup-project/action.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/schema-eas.yml, .github/workflows/schema-metadata.yml, .github/workflows/schema-xdl.yml, .github/workflows/test.yml
=> chore: bump all workflow actions to latest versions

.github/actions/package-version/action.yml, .github/workflows/schema-eas.yml, .github/workflows/schema-metadata.yml, .github/workflows/schema-xdl.yml
This removes a warning from GHA and helps clean up the workflows.
=> chore: use composite action to resolve exact npm package version

src/__tests__/commands/code-provider.e2e.ts, src/__tests__/commands/preview-config.e2e.ts, src/__tests__/commands/preview-modifier-json.e2e.ts, src/__tests__/commands/preview-modifier.e2e.ts, src/__tests__/extension.e2e.ts, src/__tests__/manifestAssetCompletions.e2e.ts, src/__tests__/manifestDiagnostics.e2e.ts, src/__tests__/manifestLinks.e2e.ts, src/__tests__/manifestPluginCompletions.e2e.ts, src/__tests__/schemas/eas-metadata.e2e.ts, src/__tests__/schemas/eas.e2e.ts, src/__tests__/schemas/expo-module.e2e.ts, src/__tests__/schemas/expo-xdl.e2e.ts, src/__tests__/utils/vscode.ts, src/__tests__/utils/wait.ts, src/expo/__tests__/project.test.ts, src/expoDebuggers.ts, src/manifestDiagnostics.ts, src/manifestLinks.ts, src/manifestPluginCompletions.ts, src/preview/ExpoConfigCodeProvider.ts, src/preview/IntrospectCodeProvider.ts, src/settings.ts, src/types.d.ts, src/utils/cache.ts, src/utils/telemetry.ts, test/mocha/vscode-runner.ts, webpack.config.js
Various small changes should improve QOL and maintenance.
=> refactor: project quality of life improvements

src/manifestAssetCompletions.ts, src/manifestDiagnostics.ts, src/manifestLinks.ts, src/manifestPluginCompletions.ts, src/settings.ts
Small optimization when changing configuration of vscode.
=> refactor: only re-fetch config when affected
